src/UI/LiveMedyCase.Web/ViewModels/UserViewModels.cs
using System.ComponentModel.DataAnnotations;
using LiveMedyCase.Data.Model.Enums;

namespace LiveMedyCase.Web.ViewModels
{
    public class UserLoginViewModel
    {
        [Required]
        public string Username { get; set; }
		[Required]
		public string Password { get; set; }
		[Required]
		public string Token { get; set; }
    }

    public class UserRegisterViewModel
    {
        [Required]
        public string Username { get; set; }
        [Required]
        public string Password { get; set; }
        [Required]
		[Compare("Password")]
		public string ConfirmPassword { get; set; }
        public string? Referrer { get; set; }
        [Required]
        public string Token { get; set; }
    }

    public class UserInfoViewModel
    {
		public string ReferralCode { get; set; }
		public string Username { get; set; }
		public RoleTypes RoleType { get; set; }
		public string Role => RoleType.ToString();
	}
}

src/UI/LiveMedyCase.Web/Controllers/AuthController.cs
using LiveMedyCase.Business.Services.Base;
using LiveMedyCase.Web.Utils.ReCaptcha;
using LiveMedyCase.Web.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.RateLimiting;

namespace LiveMedyCase.Web.Controllers
{
	public class AuthController : Controller
	{
		private readonly IAuthService _authService;
		private readonly IRecaptchaValidator _recaptchaValidator;

		public AuthController(IAuthService authService, IRecaptchaValidator recaptchaValidator)
		{
			_authService = authService;
			_recaptchaValidator = recaptchaValidator;
		}

		public IActionResult SignIn()
		{
			return View(new UserLoginViewModel());
		}

		[ValidateAntiForgeryToken]
		[HttpPost]
		public async Task<IActionResult> SignIn(UserLoginViewModel model)
		{
			if (!_recaptchaValidator.IsRecaptchaValid(model.Token))
			{
				TempData["Message"] = "Recaptcha Error";
				return View(model);
			}

			if (ModelState.IsValid)
			{
				var result = await _authService.SignInAsync(new(Username: model.Username,
																Password: model.Password));
				if (!result.Success)
				{
					TempData["Message"] = result.Message;
					return View(model);
				}

				return RedirectToAction("Index", "Home");
			}

			TempData["Message"] = "Login Error";
			return View(model);
		}

		[EnableRateLimiting("ReferralRate")]
		public IActionResult SignUp(string referralCode)
		{
			return View(new UserRegisterViewModel { Referrer = referralCode });
		}

		[ValidateAntiForgeryToken]
		[HttpPost]
		public async Task<IActionResult> SignUp(UserRegisterViewModel model)
		{
			if (!_recaptchaValidator.IsRecaptchaValid(model.Token))
			{
				TempData["Message"] = "Recaptcha Error";
				return View(model);
			}

			if (ModelState.IsValid)
			{
				var result = await _authService.SignUpAsync(new(Username: model.Username,
																Password: model.Password,
																Referrer: model.Referrer));
				if (result.Success)
				{
					TempData["Message"] = result.Message;
					return RedirectToAction("SignIn", "Auth");
				}
				else
				{
					TempData["Message"] = result.Message;
					return View(model);
				}
			}

			TempData["Message"] = "Registration error";
			return View(model);
		}

		public new async Task<IActionResult> SignOut()
		{
			await _authService.SignOutAsync();
			TempData["Message"] = "Has Been Sign Out";
			return RedirectToAction("SignIn", "Auth");
		}
	}
}

src/UI/LiveMedyCase.Web/Controllers/HomeController.cs
using System.Data;
using LiveMedyCase.Business.Services.Base;
using LiveMedyCase.Core.Constants;
using LiveMedyCase.Data.Model.Enums;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace LiveMedyCase.Web.Controllers
{
	public class HomeController : Controller
	{
		private readonly IAuthService _authService;
		private readonly IUserService _userService;

		public HomeController(IAuthService authService, IUserService userService)
		{
			_authService = authService;
			_userService = userService;
		}

		public async Task<IActionResult> Index()
		{
			var result = await _authService.GetSignInUserAsync();
			if (result.Success)
			{
				if (result.Data?.Role == RoleTypes.Admin)
					return RedirectToAction("AdminDashboard", "Home");
				else
					return RedirectToAction("Dashboard", "Home");
			}

			return RedirectToAction("SignIn", "Auth");
		}

		[Authorize(Roles = RoleConsts.AdminRole)]
		public async Task<IActionResult> AdminDashboard()
		{
			var result = await _userService.GetUserSummariesAsync();
			if (result.Success)
				return View(result.Data);
			else
				return View();
		}

		[Authorize]
		public async Task<IActionResult> Dashboard()
		{
			return View();
		}

	}
}

src/UI/LiveMedyCase.Web/ViewComponents/UserInfoViewComponent.cs
using LiveMedyCase.Business.Services.Base;
using LiveMedyCase.Web.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace LiveMedyCase.Web.ViewComponents
{
	public class UserInfoViewComponent : ViewComponent
	{
		private readonly IAuthService _authService;

		public UserInfoViewComponent(IAuthService authService)
		{
			_authService = authService;
		}

		public async Task<IViewComponentResult> InvokeAsync()
		{
			var result = await _authService.GetSignInUserAsync();
			if (result.Success)
				return View(new UserInfoViewModel
				{
					Username = result.Data!.Username,
					RoleType = result.Data!.Role,
					ReferralCode = result.Data!.ReferralCode
				});

			return View();
		}
	}
}

src/UI/LiveMedyCase.Web/Views/Home/AdminDashboard.cshtml
@model List<UserSummaryInfoResponse>
@{
	Layout = "_Layout";
	ViewData["Title"] = "Dashboard";
	var message = TempData["Message"]?.ToString();
}
<hr />
<h1>Summaries</h1>
@if(Model!= null && Model.Any())
{
	foreach(var summary in Model)
	{
		<li>Role : @summary.Role - Count : @summary.Count</li>
	}
	<br />
}
<br />
@await Component.InvokeAsync("UserInfo")

src/UI/LiveMedyCase.Web/Views/Home/Dashboard.cshtml
@{
	Layout = "_Layout";
	ViewData["Title"] = "Dashboard";
	var message = TempData["Message"]?.ToString();
}

@await Component.InvokeAsync("UserInfo")

src/UI/LiveMedyCase.Web/Views/Shared/Components/UserInfo/Default.cshtml
@model UserInfoViewModel
<hr />
<h1>User Info</h1>
<ul>
	<li>Username : @Model.Username</li>
	<li>Role : @Model.Role</li>
	<li><a asp-controller="Auth" asp-action="SignUp" asp-route-referrercode="@Model.ReferralCode">Referrer Link</a></li>
	<a asp-controller="Auth" asp-action="SignOut">SignOut</a>
</ul>
<hr />

src/UI/LiveMedyCase.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="cyaras">
    <meta name="keywords" content="case">

    <title>@ViewData["Title"]</title>

    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;600&display=swap" rel="stylesheet">
</head>
<body class="background-image-2">
    <main class="d-flex w-100">
        <div class="container d-flex flex-column">
            <div class="row vh-100">
                <div class="col-sm-10 col-md-8 col-lg-6 mx-auto d-table h-100">
                    <div class="d-table-cell align-middle">
                        @RenderBody()
                    </div>
                </div>
            </div>
        </div>
    </main>

    @RenderSection("Scripts", required: false)
@*    <script src="~/libs/jquery/jquery.min.js"></script>
    <script src="~/libs/jquery-validate/jquery.validate.min.js"></script>
    <script src="~/libs/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>*@
</body>
</html>